// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeolq8Mi6GC71_fs1Sf6QMoKB7qAIiu7s',
    appId: '1:691564711424:web:7d1d3be2aaa677f46ed2e5',
    messagingSenderId: '691564711424',
    projectId: 'crud-f44d7',
    authDomain: 'crud-f44d7.firebaseapp.com',
    storageBucket: 'crud-f44d7.appspot.com',
    measurementId: 'G-1YJY837PKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzdNG1Dk2B7SAhc5JTc-6_wWmjvNnVjc4',
    appId: '1:691564711424:android:3bcaf0d02abbd0676ed2e5',
    messagingSenderId: '691564711424',
    projectId: 'crud-f44d7',
    storageBucket: 'crud-f44d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6h8qScwiZc1n6wEEnQfXan01siIcbLGo',
    appId: '1:691564711424:ios:aa86252afd902d5e6ed2e5',
    messagingSenderId: '691564711424',
    projectId: 'crud-f44d7',
    storageBucket: 'crud-f44d7.appspot.com',
    iosBundleId: 'com.example.flutterPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6h8qScwiZc1n6wEEnQfXan01siIcbLGo',
    appId: '1:691564711424:ios:aa86252afd902d5e6ed2e5',
    messagingSenderId: '691564711424',
    projectId: 'crud-f44d7',
    storageBucket: 'crud-f44d7.appspot.com',
    iosBundleId: 'com.example.flutterPractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeolq8Mi6GC71_fs1Sf6QMoKB7qAIiu7s',
    appId: '1:691564711424:web:e9efd4d16093fb976ed2e5',
    messagingSenderId: '691564711424',
    projectId: 'crud-f44d7',
    authDomain: 'crud-f44d7.firebaseapp.com',
    storageBucket: 'crud-f44d7.appspot.com',
    measurementId: 'G-8TNJEHX2BR',
  );
}
